Historychart
Alicelidel/banki_parcer pull request #11
Opened 2017-08-23 10:12 UTC by Alicelidel

следующим пунктом - тесты

2017-08-24 06:13 UTC, den-gts commented on get_info.py
> +    money = money.split(' ')
Тут лучше заменить пробелы с помощью replace

2017-08-24 06:13 UTC, den-gts commented on rocket.py
> +make_json(results)
А почему json нам бы не сохранить в переменную? Тем самым избавимся от временного файла.

2017-08-24 06:13 UTC, den-gts commented on rocket.py
> +#посчитаем финансы банка "открытие" за полгода и построим график
Как насчет построения графика для top10 банков? Каждая линия для одного банка

2017-08-24 06:13 UTC, den-gts commented on rocket.py
> +x = [i for i in range(2,8)]
Тут достаточно x=range(2,8). Тут i for i in фактически идет перебор и со значением i нечего не происходит

2017-08-24 17:43 UTC, Alicelidel commented on rocket.py
> +make_json(results)
а я специально делала сохранение в файл, чтобы было. встречала просто однажды задание, где было "выгрузка данных из json-файла", поэтому сделала такой "временный файл"

2017-08-24 19:10 UTC, Alicelidel commented on rocket.py
> +#посчитаем финансы банка "открытие" за полгода и построим график
сделано)

2017-08-25 05:33 UTC, den-gts requested changes
вообще стоит как элементарные куски кода в функции переместить... например, процедуру вычисление дата сета для одного банка, затем другая функция вычисление дата сетов для всех банков, в которой уже будет вызываться первая. Легче читать будет и больше возможность переиспользования кода.

2017-08-25 05:33 UTC, den-gts commented on get_info.py
> +    money = money.split(' ')
Да и вообще правильней перевести строку в число

2017-08-25 05:33 UTC, den-gts commented on get_info.py
> +    """функция, которая достаёт данные из json"""
а почему бы нам json  не сохранять в память и не создавать временный файл?

2017-08-25 05:33 UTC, den-gts commented on get_info.py
> +    """функция получения значения месяцев для вычисления активов банка"""
все уже придумано до нас. https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

2017-08-25 05:33 UTC, den-gts commented on get_info.py
> +    x = range(2,8)
текущий месяц можно вычислить из https://docs.python.org/2/library/datetime.html#datetime.date.today

2017-08-25 05:33 UTC, den-gts commented on rocket.py
> +    bank_id = re.match(r'\s+([\d]+)\s+', bank_id).group(1)
и не принципиальное замечение... квадратные скобки тут не обезательны.. так как фактически в них один символ

2017-08-25 05:33 UTC, den-gts commented on rocket.py
> +    bank_name = re.findall(r'\s(\w[\D]+\d*\w\D)\s', bank_name)[0]
тоже бы в re.match

2017-08-25 05:33 UTC, den-gts commented on rocket.py
> +bank_id = int(input('\nДля построения финансовых показателей ведите номер интересующего банка в соответствие с таблицей(от 1 до 50): '))
а зачем мы ожидаем ввод пользователя? это дебажная строчка?

2017-08-25 05:33 UTC, den-gts commented on rocket.py
> +print('Теперь построим график активов топ-10 банков')
вроде там все 50

2017-08-25 11:11 UTC, Alicelidel commented on rocket.py
> +    bank_id = re.match(r'\s+([\d]+)\s+', bank_id).group(1)
там не один, там от 1 до 50 номер.
вся строчка которую я выбираю содержит в себе кучу пробелов по бокам и место и сдвиг в рейтинге, типа - (     8 -2   ), поэтому квадратные скобки. можно было бы конечно ещё написать \d{1,2}

2017-08-25 11:13 UTC, Alicelidel commented on rocket.py
> +bank_id = int(input('\nДля построения финансовых показателей ведите номер интересующего банка в соответствие с таблицей(от 1 до 50): '))
строится график любого из банков, сделаю выбор id рандомно

2017-08-25 13:03 UTC, den-gts commented on rocket.py
> +bank_id = int(input('\nДля построения финансовых показателей ведите номер интересующего банка в соответствие с таблицей(от 1 до 50): '))
Рандомно не очень. Давай лучше самого лучшего наградим:)

2017-08-25 13:28 UTC, Alicelidel commented on get_info.py
> +    """функция, которая достаёт данные из json"""
тогда будет использоваться json.dumps, потому что dump не работает без file-like object

2017-08-25 13:30 UTC, Alicelidel commented on rocket.py
> +print('Теперь построим график активов топ-10 банков')
почему 50?

2017-08-25 19:01 UTC, den-gts commented on get_info.py
> +    """функция, которая достаёт данные из json"""
само-собой. нечего криминального в  json.dumps нет. Он даже чаще используется чем json.dump

2017-08-25 19:09 UTC, den-gts commented on rocket.py
> +    bank_id = re.match(r'\s+([\d]+)\s+', bank_id).group(1)
я про ```[\d]+``` тоже самое что ```\d+``` [] нужно для обозначения набора символов. Например, хотим найти фразу в нижнем регистре, тогда нас выручат []. ```[a-z]+```. читается как повторит символ от а до z от 1 до бесконечности. А ```\d+``` читается как повторить спец символ \d (цифра) от 1 до бесконечности.

2017-08-25 19:44 UTC, Alicelidel commented on rocket.py
> +    bank_id = re.match(r'\s+([\d]+)\s+', bank_id).group(1)
всё, я поняла, спасибо))

2017-08-25 19:48 UTC, den-gts requested changes

2017-08-25 19:48 UTC, den-gts commented on rocket.py
> +print('Теперь построим график активов топ-10 банков')
ага.. увидел непривычную строчку 99

2017-08-25 19:48 UTC, den-gts commented on rocket.py
> +for id in range(1,11):
лучше вот так:
```python
for bank in results[:10].sorted(key=...):
    ...
```
sorted для сортировки по активам. Соответсвенно в  key надо написать сортировать по активам

2017-08-25 19:48 UTC, den-gts commented on rocket.py
> +#теперь, имея ссылку на страницу банка, мы можем посчитать финансы за полгода
и лучше удалять закоментированные строки. их можно будет из git востановть.. а читаемость от их наличия страдает

2017-08-25 19:48 UTC, den-gts commented on make_info.py
> +import matplotlib.pyplot as plt
а он теперь используется?

2017-08-25 19:59 UTC, den-gts commented
И комментарии к коду это очень здорово. Но злоупотреблять ими тоже не следует. Например, комментировать очевидные вещи. Лишние комментарии ухудшают читаемость.  Мне очень понравился доклад на эту тему https://youtu.be/-SRUctRR_4s

2017-08-26 11:07 UTC, Alicelidel commented on make_info.py
> +import matplotlib.pyplot as plt
с помощью plotly я строю таблицу, с помощью pyplot - графики

2017-08-26 16:12 UTC, den-gts commented on make_info.py
> +import matplotlib.pyplot as plt
А не получилось с помощью plotly строить графики?

2017-08-26 16:30 UTC, den-gts commented on get_info.py
> +    for i in range(1,7):
А что такое 1,7?

2017-08-26 16:30 UTC, den-gts commented on get_info.py
> +    bank_name = re.match(r'\s+(\S[\S\s]+\S)\s', bank_name).group(1)
а точно \S тут уместен? может лучше \w? под \S попадает всякие ```\_#$```
а [\S\s] это как? пробельный символ или не пробельный символ. ```[\S\s]``` == ```.+```

2017-08-26 16:30 UTC, den-gts commented on get_info.py
> +    bank_hidden_id = re.match(r'.*(\?BANK_ID=[0-9]+).*', bank_url).group(1)
Кстати ```[0-9]``` можно заменить на ```\d```

2017-08-26 16:30 UTC, den-gts commented on make_info.py
> +    temp_doc = json.dumps(banks, sort_keys=True, indent=4, separators=(',', ' : '))
а зачем нам что то передавать в separators? Я даже до этого и не знал об этом аргументе:)

2017-08-26 16:30 UTC, den-gts commented
И давай уберем banks.json. Он теперь не очень нужен

2017-08-26 18:43 UTC, Alicelidel commented on get_info.py
> +    bank_name = re.match(r'\s+(\S[\S\s]+\S)\s', bank_name).group(1)
в названии может быть ещё дефис и кавычки, поэтому я выбрала любой непробельный символ, поэтому \S.
\S\s заменю на .+, не подумала, так действительно проще

2017-08-28 09:40 UTC, closed without merging