Geturl
Alicelidel/banki_parcer pull request #8
Opened 2017-08-16 10:44 UTC by Alicelidel

@den-gts по другому упомянуть у меня не получается

усложнила скрипт
он вытягивает описание банка
к сожалению, со страницы рейтинга нет прямого перехода на ссылку с описанием банка, поэтому у меня так сложно вышло

2017-08-16 13:51 UTC, den-gts requested changes

2017-08-16 13:51 UTC, den-gts commented on rocket.py
> +    #получаем ссылку для перехода на страницу банка
Напрашивается получение описания каждого банка по ссылке перенести в функцию, которая а качестве аргумента принимает банк. А то структура становиться сложной

2017-08-16 17:22 UTC, Alicelidel commented
лучше было бы сделать base_url, поэтому я поменяла ссылки

2017-08-17 05:25 UTC, den-gts requested changes

2017-08-17 05:25 UTC, den-gts commented on get_desc.py
> +    # ссылка на описание банка лежит на том же url, но от исходного url надо убрать лишнее, оставив только www.banki.ru
коменнтарий уже устарел

2017-08-17 05:25 UTC, den-gts commented on get_desc.py
> +def get_desc(url2):
url2 - это же по сути bank_name?

2017-08-17 13:39 UTC, den-gts approved these changes

2017-08-17 14:18 UTC, merged